package com.pascal.ezload.service.dashboard;

public enum ChartIndex {
    CURRENT_SHARES,
    TEN_WITH_MOST_IMPACTS,
    ALL_SHARES,
    CUMUL_VALEUR_PORTEFEUILLE_SANS_DIVIDENDES,
    CUMUL_VALEUR_PORTEFEUILLE_AVEC_DIVIDENDES,
    CUMUL_LIQUIDITE,
    CUMUL_ENTREES_SORTIES,
    INSTANT_ENTREES_SORTIES,
    INSTANT_DIVIDENDES,
    CUMUL_DIVIDENDES,
    CURRENCIES

}
