package com.pascal.ezload.service.dashboard;

public enum ChartIndexPerf {
    PERF_VALEUR_PORTEFEUILLE_SANS_DIVIDENDES,
    PERF_VALEUR_PORTEFEUILLE_AVEC_DIVIDENDES,
    PERF_CROISSANCE_CURRENT_SHARES,
    PERF_RENDEMENT_CURRENT_SHARES,
    PERF_CROISSANCE_RENDEMENT_CURRENT_SHARES
}
